---
- hosts: localhost
  connection: local 
  become: true

  tasks:

  - name: remove ansible user
    user:
      name: simone
      state: absent
      remove: yes

  - name: install vim-nox
    package: 
     name: 
        - vim-nox
        - python3-psutil

